"use client";

import { ToolPageWrapper } from "@/components/ToolPageWrapper";
import { CheatSheet, CheatItem } from "@/components/CheatSheet";

const categories = ["Nacos 服务注册", "Nacos 配置中心", "配置中心", "OpenFeign 远程调用", "Gateway 网关", "Sentinel 限流熔断", "负载均衡", "Seata 分布式事务", "消息驱动", "链路追踪", "服务保护", "常用依赖"];

const items: CheatItem[] = [
  { category: "Nacos 服务注册", title: "引入依赖", description: "添加 Nacos 服务发现依赖", code: "<dependency>\n    <groupId>com.alibaba.cloud</groupId>\n    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>\n</dependency>" },
  { category: "Nacos 服务注册", title: "配置注册中心", description: "配置 Nacos 服务器地址", code: "spring:\n  application:\n    name: order-service\n  cloud:\n    nacos:\n      discovery:\n        server-addr: 127.0.0.1:8848\n        namespace: dev\n        group: DEFAULT_GROUP" },
  { category: "Nacos 服务注册", title: "启用服务发现", description: "主类启用注解", code: "@SpringBootApplication\n@EnableDiscoveryClient\npublic class OrderApplication {\n    public static void main(String[] args) {\n        SpringApplication.run(OrderApplication.class, args);\n    }\n}" },
  { category: "Nacos 服务注册", title: "命名空间隔离", description: "多环境隔离（dev/test/prod）", code: "spring:\n  cloud:\n    nacos:\n      discovery:\n        server-addr: 127.0.0.1:8848\n        namespace: a1b2c3d4-e5f6-7890-abcd-ef1234567890" },
  { category: "Nacos 服务注册", title: "服务分组与元数据", description: "服务分组及自定义元数据", code: "spring:\n  cloud:\n    nacos:\n      discovery:\n        group: ORDER_GROUP\n        metadata:\n          version: v1\n          region: cn-north" },

  { category: "Nacos 配置中心", title: "引入依赖", description: "添加 Nacos 配置中心依赖", code: "<dependency>\n    <groupId>com.alibaba.cloud</groupId>\n    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>\n</dependency>\n<dependency>\n    <groupId>org.springframework.cloud</groupId>\n    <artifactId>spring-cloud-starter-bootstrap</artifactId>\n</dependency>" },
  { category: "Nacos 配置中心", title: "bootstrap 配置", description: "bootstrap.yml 连接配置中心", code: "# bootstrap.yml\nspring:\n  application:\n    name: order-service\n  cloud:\n    nacos:\n      config:\n        server-addr: 127.0.0.1:8848\n        file-extension: yaml\n        namespace: dev\n        group: DEFAULT_GROUP\n        shared-configs:\n          - data-id: common.yaml\n            refresh: true" },
  { category: "Nacos 配置中心", title: "配置分组", description: "按 group 区分不同配置", code: "spring:\n  cloud:\n    nacos:\n      config:\n        group: PAYMENT_GROUP\n        extension-configs:\n          - data-id: payment.yaml\n            group: PAYMENT_GROUP\n            refresh: true" },
  { category: "Nacos 配置中心", title: "动态刷新", description: "配置动态刷新", code: "@RestController\n@RefreshScope\npublic class ConfigController {\n\n    @Value(\"${app.switch.enabled:false}\")\n    private boolean switchEnabled;\n\n    @GetMapping(\"/config\")\n    public boolean getConfig() {\n        return switchEnabled;\n    }\n}" },

  { category: "配置中心", title: "Config Server 依赖", description: "Spring Cloud Config 服务端", code: "<dependency>\n    <groupId>org.springframework.cloud</groupId>\n    <artifactId>spring-cloud-config-server</artifactId>\n</dependency>" },
  { category: "配置中心", title: "Config Server 启动", description: "启用配置服务并指定仓库", code: "@SpringBootApplication\n@EnableConfigServer\npublic class ConfigServerApplication { }\n\n# application.yml\nspring:\n  cloud:\n    config:\n      server:\n        git:\n          uri: https://github.com/xxx/config-repo\n          default-label: main" },
  { category: "配置中心", title: "Config Client bootstrap", description: "客户端连接 Config Server", code: "spring:\n  application:\n    name: order-service\n  cloud:\n    config:\n      uri: http://localhost:8888\n      profile: dev\n      label: main" },
  { category: "配置中心", title: "配置加密", description: "Jasypt 加密敏感配置", code: "<dependency>\n    <groupId>com.github.ulisesbocchio</groupId>\n    <artifactId>jasypt-spring-boot-starter</artifactId>\n</dependency>\n\n# 加密后配置\napp.secret=ENC(加密后的密文)\njasypt.encryptor.password=密钥" },

  { category: "OpenFeign 远程调用", title: "引入依赖", description: "添加 OpenFeign 依赖", code: "<dependency>\n    <groupId>org.springframework.cloud</groupId>\n    <artifactId>spring-cloud-starter-openfeign</artifactId>\n</dependency>\n<dependency>\n    <groupId>org.springframework.cloud</groupId>\n    <artifactId>spring-cloud-starter-loadbalancer</artifactId>\n</dependency>" },
  { category: "OpenFeign 远程调用", title: "启用 Feign", description: "主类启用 FeignClients", code: "@SpringBootApplication\n@EnableFeignClients\npublic class OrderApplication { }" },
  { category: "OpenFeign 远程调用", title: "定义 Feign 接口", description: "声明式远程调用接口", code: "@FeignClient(name = \"user-service\", fallbackFactory = UserClientFallback.class)\npublic interface UserClient {\n\n    @GetMapping(\"/api/users/{id}\")\n    User getById(@PathVariable(\"id\") Long id);\n\n    @PostMapping(\"/api/users\")\n    User create(@RequestBody UserDTO dto);\n}" },
  { category: "OpenFeign 远程调用", title: "降级处理", description: "Feign 调用失败的兜底", code: "@Component\npublic class UserClientFallback implements FallbackFactory<UserClient> {\n    @Override\n    public UserClient create(Throwable cause) {\n        return new UserClient() {\n            @Override\n            public User getById(Long id) {\n                return new User(id, \"未知用户\");\n            }\n            @Override\n            public User create(UserDTO dto) {\n                throw new RuntimeException(\"服务不可用\");\n            }\n        };\n    }\n}" },
  { category: "OpenFeign 远程调用", title: "请求拦截器", description: "传递 Token 等请求头", code: "@Configuration\npublic class FeignConfig {\n    @Bean\n    public RequestInterceptor requestInterceptor() {\n        return template -> {\n            ServletRequestAttributes attrs = (ServletRequestAttributes)\n                RequestContextHolder.getRequestAttributes();\n            if (attrs != null) {\n                String token = attrs.getRequest().getHeader(\"Authorization\");\n                if (token != null) template.header(\"Authorization\", token);\n            }\n        };\n    }\n}" },
  { category: "OpenFeign 远程调用", title: "错误解码器", description: "自定义 Feign 异常解析", code: "@Component\npublic class FeignErrorDecoder implements ErrorDecoder {\n    private final ErrorDecoder defaultDecoder = new Default();\n    @Override\n    public Exception decode(String methodKey, Response response) {\n        if (response.status() == 404)\n            return new NotFoundException(\"资源不存在\");\n        if (response.status() >= 500)\n            return new ServiceException(\"远程服务异常\");\n        return defaultDecoder.decode(methodKey, response);\n    }\n}" },
  { category: "OpenFeign 远程调用", title: "Feign 配置", description: "超时、日志等配置", code: "feign:\n  client:\n    config:\n      default:\n        connect-timeout: 5000\n        read-timeout: 10000\n        logger-level: FULL\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n\nlogging:\n  level:\n    com.example.client: DEBUG" },

  { category: "Gateway 网关", title: "引入依赖", description: "添加 Gateway 依赖", code: "<dependency>\n    <groupId>org.springframework.cloud</groupId>\n    <artifactId>spring-cloud-starter-gateway</artifactId>\n</dependency>" },
  { category: "Gateway 网关", title: "路由配置", description: "配置路由转发规则", code: "spring:\n  cloud:\n    gateway:\n      routes:\n        - id: user-service\n          uri: lb://user-service\n          predicates:\n            - Path=/api/users/**\n          filters:\n            - StripPrefix=0\n        - id: order-service\n          uri: lb://order-service\n          predicates:\n            - Path=/api/orders/**" },
  { category: "Gateway 网关", title: "AddRequestHeader 过滤器", description: "向下游添加请求头", code: "spring:\n  cloud:\n    gateway:\n      routes:\n        - id: user-service\n          uri: lb://user-service\n          predicates:\n            - Path=/api/users/**\n          filters:\n            - AddRequestHeader=X-Request-Source, gateway\n            - AddRequestHeader=X-Request-Time, ${T(java.time.Instant).now()}" },
  { category: "Gateway 网关", title: "StripPrefix / RewritePath", description: "路径重写过滤器", code: "filters:\n  - StripPrefix=1\n  - RewritePath=/api/v1/(?<segment>.*), /${segment}\n\n# StripPrefix=1: /api/users/1 -> /users/1\n# RewritePath: /api/v1/orders -> /orders" },
  { category: "Gateway 网关", title: "Retry 过滤器", description: "失败重试配置", code: "filters:\n  - name: Retry\n    args:\n      retries: 3\n      statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE\n      methods: GET\n      backoff:\n        firstBackoff: 10ms\n        maxBackoff: 50ms\n        factor: 2" },
  { category: "Gateway 网关", title: "全局过滤器", description: "自定义全局过滤器（如鉴权）", code: "@Component\npublic class AuthFilter implements GlobalFilter, Ordered {\n\n    @Override\n    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {\n        String token = exchange.getRequest().getHeaders().getFirst(\"Authorization\");\n        if (token == null || token.isEmpty()) {\n            exchange.getResponse().setStatusCode(HttpStatus.UNAUTHORIZED);\n            return exchange.getResponse().setComplete();\n        }\n        return chain.filter(exchange);\n    }\n\n    @Override\n    public int getOrder() { return 0; }\n}" },
  { category: "Gateway 网关", title: "跨域配置", description: "Gateway 全局跨域设置", code: "spring:\n  cloud:\n    gateway:\n      globalcors:\n        cors-configurations:\n          '[/**]':\n            allowedOrigins: \"*\"\n            allowedMethods: \"*\"\n            allowedHeaders: \"*\"" },

  { category: "Sentinel 限流熔断", title: "引入依赖", description: "添加 Sentinel 依赖", code: "<dependency>\n    <groupId>com.alibaba.cloud</groupId>\n    <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>\n</dependency>" },
  { category: "Sentinel 限流熔断", title: "连接控制台", description: "配置 Sentinel Dashboard", code: "spring:\n  cloud:\n    sentinel:\n      transport:\n        dashboard: 127.0.0.1:8080\n        port: 8719" },
  { category: "Sentinel 限流熔断", title: "注解限流", description: "使用注解定义限流规则", code: "@GetMapping(\"/api/orders/{id}\")\n@SentinelResource(value = \"getOrder\",\n    blockHandler = \"getOrderBlock\",\n    fallback = \"getOrderFallback\")\npublic Order getOrder(@PathVariable Long id) {\n    return orderService.findById(id);\n}\n\npublic Order getOrderBlock(Long id, BlockException e) {\n    return new Order(id, \"限流了，请稍后重试\");\n}\n\npublic Order getOrderFallback(Long id, Throwable t) {\n    return new Order(id, \"服务异常，降级处理\");\n}" },
  { category: "Sentinel 限流熔断", title: "流控规则代码配置", description: "代码中动态添加流控规则", code: "@PostConstruct\npublic void initFlowRules() {\n    List<FlowRule> rules = new ArrayList<>();\n    FlowRule rule = new FlowRule();\n    rule.setResource(\"getOrder\");\n    rule.setGrade(RuleConstant.FLOW_GRADE_QPS);\n    rule.setCount(10);\n    rules.add(rule);\n    FlowRuleManager.loadRules(rules);\n}" },
  { category: "Sentinel 限流熔断", title: "降级规则", description: "慢调用比例、异常比例熔断", code: "DegradeRule rule = new DegradeRule();\nrule.setResource(\"getOrder\");\nrule.setGrade(RuleConstant.DEGRADE_GRADE_RT);\nrule.setCount(500);\nrule.setTimeWindow(10);\nrule.setSlowRatioThreshold(0.5);\nDegradeRuleManager.loadRules(Collections.singletonList(rule));" },
  { category: "Sentinel 限流熔断", title: "热点参数限流", description: "针对参数值限流", code: "ParamFlowRule rule = new ParamFlowRule();\nrule.setResource(\"getOrder\");\nrule.setParamIdx(0);\nrule.setCount(5);\nParamFlowRuleManager.loadRules(Collections.singletonList(rule));" },
  { category: "Sentinel 限流熔断", title: "集群流控模式", description: "多实例共享流控配额", code: "spring:\n  cloud:\n    sentinel:\n      transport:\n        client-ip: 127.0.0.1\n      cluster:\n        mode: client\n        server:\n          host: 127.0.0.1\n          port: 18730" },

  { category: "负载均衡", title: "LoadBalancer 依赖", description: "Spring Cloud LoadBalancer（替代 Ribbon）", code: "<dependency>\n    <groupId>org.springframework.cloud</groupId>\n    <artifactId>spring-cloud-starter-loadbalancer</artifactId>\n</dependency>" },
  { category: "负载均衡", title: "自定义 LoadBalancer", description: "自定义负载均衡策略", code: "@Configuration\npublic class LoadBalancerConfig {\n    @Bean\n    public ReactorLoadBalancer<ServiceInstance> customLoadBalancer(\n            Environment env, LoadBalancerClientFactory factory) {\n        String name = env.getProperty(LoadBalancerClientFactory.PROPERTY_NAME);\n        return new RandomLoadBalancer(\n            factory.getLazyProvider(name, ServiceInstanceListSupplier.class), name);\n    }\n}" },
  { category: "负载均衡", title: "负载策略配置", description: "配置 LoadBalancer 策略", code: "spring:\n  cloud:\n    loadbalancer:\n      configurations: default\n      cache:\n        enabled: true" },

  { category: "Seata 分布式事务", title: "引入依赖", description: "添加 Seata 依赖", code: "<dependency>\n    <groupId>com.alibaba.cloud</groupId>\n    <artifactId>spring-cloud-starter-alibaba-seata</artifactId>\n</dependency>" },
  { category: "Seata 分布式事务", title: "配置 Seata", description: "配置 Seata 服务端地址", code: "seata:\n  application-id: order-service\n  tx-service-group: my_tx_group\n  service:\n    vgroup-mapping:\n      my_tx_group: default\n  registry:\n    type: nacos\n    nacos:\n      server-addr: 127.0.0.1:8848" },
  { category: "Seata 分布式事务", title: "AT 模式", description: "自动补偿，无侵入", code: "@GlobalTransactional(rollbackFor = Exception.class)\npublic void createOrder(OrderDTO dto) {\n    stockClient.deduct(dto.getProductId(), dto.getCount());\n    orderMapper.insert(dto);\n    accountClient.debit(dto.getUserId(), dto.getAmount());\n}" },
  { category: "Seata 分布式事务", title: "TCC 模式配置", description: "Try-Confirm-Cancel 手动控制", code: "@LocalTCC\npublic interface AccountTccService {\n    @TwoPhaseBusinessAction(name = \"debit\", commitMethod = \"confirm\", rollbackMethod = \"cancel\")\n    boolean tryDebit(BusinessActionContext ctx, Long userId, BigDecimal amount);\n    boolean confirm(BusinessActionContext ctx);\n    boolean cancel(BusinessActionContext ctx);\n}" },

  { category: "消息驱动", title: "RabbitMQ 配置", description: "Spring Cloud Stream + RabbitMQ", code: "spring:\n  cloud:\n    stream:\n      binders:\n        rabbit:\n          type: rabbit\n          environment:\n            spring:\n              rabbitmq:\n                host: localhost\n                port: 5672\n      bindings:\n        output:\n          destination: order-events\n          binder: rabbit\n        input:\n          destination: order-events\n          group: payment-group\n          binder: rabbit" },
  { category: "消息驱动", title: "Kafka 配置", description: "Spring Cloud Stream + Kafka", code: "spring:\n  cloud:\n    stream:\n      binders:\n        kafka:\n          type: kafka\n          environment:\n            spring:\n              kafka:\n                bootstrap-servers: localhost:9092\n      bindings:\n        output:\n          destination: order-events\n          binder: kafka\n        input:\n          destination: order-events\n          group: payment-group\n          binder: kafka" },
  { category: "消息驱动", title: "RocketMQ 配置", description: "Spring Cloud Stream + RocketMQ", code: "<dependency>\n    <groupId>com.alibaba.cloud</groupId>\n    <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>\n</dependency>\n\nspring:\n  cloud:\n    stream:\n      rocketmq:\n        binder:\n          name-server: 127.0.0.1:9876\n      bindings:\n        output:\n          destination: order-events\n        input:\n          destination: order-events\n          group: payment-group" },
  { category: "消息驱动", title: "发送消息", description: "生产者发送消息", code: "@Service\npublic class OrderEventProducer {\n\n    @Autowired\n    private StreamBridge streamBridge;\n\n    public void sendOrderEvent(OrderEvent event) {\n        streamBridge.send(\"output\", event);\n    }\n}" },
  { category: "消息驱动", title: "消费消息", description: "消费者接收消息", code: "@Configuration\npublic class OrderEventConsumer {\n\n    @Bean\n    public Consumer<OrderEvent> input() {\n        return event -> {\n            System.out.println(\"收到订单事件: \" + event);\n        };\n    }\n}" },

  { category: "链路追踪", title: "Micrometer + Zipkin", description: "分布式链路追踪依赖", code: "<dependency>\n    <groupId>io.micrometer</groupId>\n    <artifactId>micrometer-tracing-bridge-brave</artifactId>\n</dependency>\n<dependency>\n    <groupId>io.zipkin.reporter2</groupId>\n    <artifactId>zipkin-reporter-brave</artifactId>\n</dependency>" },
  { category: "链路追踪", title: "追踪配置", description: "配置采样率和 Zipkin 地址", code: "management:\n  tracing:\n    sampling:\n      probability: 1.0\n  zipkin:\n    tracing:\n      endpoint: http://localhost:9411/api/v2/spans" },
  { category: "链路追踪", title: "Sleuth 集成", description: "Spring Boot 2.x 使用 Sleuth", code: "<dependency>\n    <groupId>org.springframework.cloud</groupId>\n    <artifactId>spring-cloud-starter-sleuth</artifactId>\n</dependency>\n<dependency>\n    <groupId>org.springframework.cloud</groupId>\n    <artifactId>spring-cloud-sleuth-zipkin</artifactId>\n</dependency>" },
  { category: "链路追踪", title: "TraceId 传递", description: "Feign 自动传递 TraceId", code: "spring:\n  sleuth:\n    sampler:\n      probability: 1.0\nfeign:\n  client:\n    config:\n      default:\n        request-interceptors:\n          - com.example.config.TraceIdPropagationInterceptor" },

  { category: "服务保护", title: "Resilience4j 熔断器", description: "熔断、限流、重试", code: "<dependency>\n    <groupId>org.springframework.cloud</groupId>\n    <artifactId>spring-cloud-starter-circuitbreaker-reactor-resilience4j</artifactId>\n</dependency>\n\nresilience4j:\n  circuitbreaker:\n    instances:\n      default:\n        slidingWindowSize: 10\n        failureRateThreshold: 50\n        waitDurationInOpenState: 10s" },
  { category: "服务保护", title: "熔断注解", description: "使用 @CircuitBreaker 注解", code: "@CircuitBreaker(name = \"userService\", fallbackMethod = \"fallback\")\npublic User getUser(Long id) {\n    return userClient.getById(id);\n}\n\npublic User fallback(Long id, Exception e) {\n    return new User(id, \"服务暂不可用\");\n}" },
  { category: "服务保护", title: "重试模式", description: "配置重试次数与退避策略", code: "resilience4j:\n  retry:\n    instances:\n      default:\n        maxAttempts: 3\n        waitDuration: 500ms\n        enableExponentialBackoff: true\n        exponentialBackoffMultiplier: 2" },

  { category: "常用依赖", title: "BOM 版本管理", description: "Spring Cloud Alibaba 版本管理", code: "<dependencyManagement>\n    <dependencies>\n        <dependency>\n            <groupId>org.springframework.cloud</groupId>\n            <artifactId>spring-cloud-dependencies</artifactId>\n            <version>2023.0.0</version>\n            <type>pom</type>\n            <scope>import</scope>\n        </dependency>\n        <dependency>\n            <groupId>com.alibaba.cloud</groupId>\n            <artifactId>spring-cloud-alibaba-dependencies</artifactId>\n            <version>2023.0.0.0</version>\n            <type>pom</type>\n            <scope>import</scope>\n        </dependency>\n    </dependencies>\n</dependencyManagement>" },
  { category: "常用依赖", title: "版本对照表", description: "Spring Boot / Cloud / Alibaba 版本关系", code: "Spring Boot 3.2.x → Spring Cloud 2023.0.x → Alibaba 2023.0.x\nSpring Boot 3.0.x → Spring Cloud 2022.0.x → Alibaba 2022.0.x\nSpring Boot 2.7.x → Spring Cloud 2021.0.x → Alibaba 2021.0.x\nSpring Boot 2.6.x → Spring Cloud 2021.0.x → Alibaba 2021.0.x\n\n注意: Spring Boot 3.x 需要 Java 17+" },
];

export default function SpringCloudCheatSheetPage() {
  return (
    <ToolPageWrapper>
      <CheatSheet
        title="Spring Cloud 速查手册"
        subtitle="Spring Cloud Alibaba 微服务组件配置速查：Nacos、Feign、Gateway、Sentinel、Seata 等"
        items={items}
        categories={categories}
      />
    </ToolPageWrapper>
  );
}
